import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar is fully auto-generated from the `docs/` directory tree, which is itself
 * generated by `scripts/migrate.ts` from the repository's original content folders.
 *
 * Folder order, labels, and collapsed state are controlled per-folder by the
 * `_category_.json` files that the migration script emits. This keeps the website
 * navigation a faithful mirror of the repository structure while allowing polished
 * display labels and manual overrides where needed.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
